### ISSUE TITLE
Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by rjzevallos** [khanld/ASR-Wav2vec-Finetune#6]
When I try to run: python train.py -c config.toml

I get this:

Traceback (most recent call last):
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/train.py", line 16, in <module>
    from utils.metric import Metric
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/utils/metric.py", line 1, in <module>
    from datasets import load_metric
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/datasets/__init__.py", line 37, in <module>
    from .arrow_dataset import Dataset, concatenate_datasets
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 53, in <module>
    from huggingface_hub import HfApi, HfFolder
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/huggingface_hub/__init__.py", line 63, in <module>
    from .keras_mixin import (
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/huggingface_hub/keras_mixin.py", line 24, in <module>
    import tensorflow as tf
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/homedtic/rzevallos/ASR-Wav2vec-Finetune/venv/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by Shaobo-Z** [comment]
You can add the following line to the requirement.txt. 
protobuf==3.20.*
